(fix) Revert SocialNetwork: add pipeline for redis cluster - fix Docker build
Revert latest change to HomeTimelineHandler.h, it's breaking Docker image build with following exception:
/social-network-microservices/src/HomeTimelineService/HomeTimelineHandler.h:129:55: error: 'class sw::redis::RedisCluster' has no member named 'get_shards_pool'